### ISSUE TITLE
Mistake in PSTQ Evaluation

### ISSUE THREAD

**Issue by archishou** [SebLague/Chess-AI#13]
https://github.com/SebLague/Chess-AI/blob/d0832f8f1d32ddfb95525d1f1e5b772a367f272e/Assets/Scripts/Core/PieceSquareTable.cs#L5

I believe this line should be !isWhite. The PSTQ is already given in white's perspective. We should only be switching when black. Please let me know if I'm misunderstanding.

**Comment by SebLague** [comment]
Hi, it is correct, but definitely confusing. My engine considers a1 to be square 0, whereas the square with index 0 in the piece square tables is a8. (Technically I should be doing 'file = 7-file' to properly convert, but the tables are symmetric along the files so it doesn't matter). I hope that makes sense!
